# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [
    # "vfio_pci"
    # "vfio"
    # "vfio_iommu_type1"
    "amdgpu"
  ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelParams = [
    # "amd_iommu=on"
    # "vfio-pci.ids=1002:7550,1002:ab40"
    "amd_pstate=active"
  ];
  boot.kernelModules = ["kvm-amd" "amd_3d_vcache" "ryzen_smu" "zenpower" "amd_pstate"];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    ryzen-smu
    zenpower
  ];
  boot.extraModprobeConfig = "";
  boot.blacklistedKernelModules = ["k10temp"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3577fe28-7413-40fb-9097-55d86d6addc9";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/99AB-C928";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [{device = "/dev/disk/by-uuid/bc2a4379-f845-4137-8ec9-6fe7ba1f8868";}];

  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp8s0.wakeOnLan.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.amdgpu.overdrive.enable = true;

  hardware.enableRedistributableFirmware = true;

  hardware.bluetooth.enable = true;
}
