# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/98eb6bb8-275a-4154-8501-e04275111e7b";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/5ADA-BD09";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/storage" = {
    device = "/dev/disk/by-uuid/91c2c6df-952d-4ab7-a50f-2ac2eefd7f09";
    fsType = "ext4";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/27a1055f-80c4-45a1-a724-d4e3eb2946f1"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-09a56b334841.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-292727e3490a.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-46e78d158e3e.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-59654c9a4b95.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-bd08a56808e5.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-c2517f24e6e7.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-c60e5bce78ae.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth07ace60.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth57aee1b.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6cee6e5.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
